#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoneyTracker02.Resource", IsApplication=true)]

namespace MoneyTracker02
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int btnAddBank = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int btnAddGroup = 2130968591;
			
			// aapt resource value: 0x7f04001d
			public const int btnBanks = 2130968605;
			
			// aapt resource value: 0x7f040005
			public const int btnDeleteBank = 2130968581;
			
			// aapt resource value: 0x7f040011
			public const int btnDeleteGroup = 2130968593;
			
			// aapt resource value: 0x7f040004
			public const int btnEditBank = 2130968580;
			
			// aapt resource value: 0x7f040010
			public const int btnEditGroup = 2130968592;
			
			// aapt resource value: 0x7f040007
			public const int btnExpadd = 2130968583;
			
			// aapt resource value: 0x7f04001b
			public const int btnExpencies = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int btnGroups = 2130968604;
			
			// aapt resource value: 0x7f040000
			public const int edtBankdate = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int edtBankmoney = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int edtBankname = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int edtExpdate = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int edtExpmoney = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int edtExpnote = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int edtGroupname = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int listBanks = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int listExpencies = 2130968584;
			
			// aapt resource value: 0x7f040012
			public const int listGroups = 2130968594;
			
			// aapt resource value: 0x7f04000b
			public const int spinnerExpbanks = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int spinnerExpgroup = 2130968586;
			
			// aapt resource value: 0x7f040014
			public const int txtBankdate = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int txtBankmoney = 2130968597;
			
			// aapt resource value: 0x7f040013
			public const int txtBankname = 2130968595;
			
			// aapt resource value: 0x7f040018
			public const int txtExpbank = 2130968600;
			
			// aapt resource value: 0x7f040016
			public const int txtExpdate = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int txtExpgroup = 2130968599;
			
			// aapt resource value: 0x7f040019
			public const int txtExpmoney = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int txtGroupname = 2130968602;
			
			// aapt resource value: 0x7f04001f
			public const int txtSpinnerBankmoney = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int txtSpinnerBankname = 2130968606;
			
			// aapt resource value: 0x7f040020
			public const int txtSpinnerGroupname = 2130968608;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Banks = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Expencies = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ExpenciesAdd = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Groups = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int list_view_Banks = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int list_view_Expencies = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int list_view_Groups = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Main = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int spinner_list_Banks = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int spinner_list_Groups = 2130837513;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
